fix(schedule): datepicker string conversion issue
Resolves a bug where clicking on a calendar date while logged out causes
the following JavaScript error:

  Uncaught TypeError: (inst.selectedMonth + 1).padStart is not a function

Ensure padStart() is called on a string, not a number, by explicitly converting the number:

  (inst.selectedMonth + 1).toString().padStart(2, '0')

Closes: #671